<?php

namespace Database\Seeders;

use App\Models\News;
use Illuminate\Database\Seeder;

class NewsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $newsList = [
            [
                'title' => 'CLP LAUNCHES A NEW PROGRAM CALLED CONNECTING STUDENTS AROUND THE WORLD (CSAW)',
                'slug' => 'connecting-students-around-the-world',
                'summary' => 'CLP’s latest project is Connecting Students around the World (C-SAW) that brings together students from two different schools in two different countries through joint projects and live video discussion. This project aims at fostering cultural communication, friendship, and what is even more important, developing understanding between youths living in different corners of the world.',
                'description' => 'CLP’s latest project is Connecting Students around the World (C-SAW) that brings together students from two different schools in two different countries through joint projects and live video discussion. This project aims at fostering cultural communication, friendship, and what is even more important, developing understanding between youths living in different corners of the world.',
                'date' => 'MAR 1, 2019',
                'youtube_url' => null,
                'image' => 'root/assets/images/connect-students/blog-img4.png',
                'status' => 'published',
            ],
            [
                'title' => 'CLP ANNUAL EVENT 2019',
                'slug' => 'clp-annual-event-2019',
                'summary' => 'Dear CLP Patron: Please attend the 2019 CLP annual event (starts at 6:00 p.m. on Saturday, August 03, 2019 at the Rutgers Cook College Campus Center, New Brunswick, NJ)and find out how your donations are helping the underprivileged youths in Bangladesh. The program flyer is pasted below.',
                'description' => 'Dear CLP Patron: Please attend the 2019 CLP annual event (starts at 6:00 p.m. on Saturday, August 03, 2019 at the Rutgers Cook College Campus Center, New Brunswick, NJ)and find out how your donations are helping the underprivileged youths in Bangladesh. The program flyer is pasted below.',
                'date' => 'JUL 5, 2019',
                'youtube_url' => null,
                'image' => 'root/assets/images/blog-img3.png',
                'status' => 'published',
            ],
            [
                'title' => 'BEXIMCO AND CLP SIGN A MOU',
                'slug' => 'beximco-and-clp-sign-a-mou',
                'summary' => 'Computer Literacy Program (CLP), USA and Dnet have signed a memorandum of understanding (MoU) with Beximco Pharmaceuticals to establish Computer Literacy Centers (CLCs). The CLCs will be established in Bhairab MP Girls High School and Bangladesh Railway High School in Bhairab, Kishoreganj and Babupur Miratuli Govt. Primary School in Chapai Nawabganj.',
                'description' => 'Computer Literacy Program (CLP), USA and Dnet have signed a memorandum of understanding (MoU) with Beximco Pharmaceuticals to establish Computer Literacy Centers (CLCs). The CLCs will be established in Bhairab MP Girls High School and Bangladesh Railway High School in Bhairab, Kishoreganj and Babupur Miratuli Govt. Primary School in Chapai Nawabganj.',
                'date' => 'AUG 29, 2019',
                'youtube_url' => null,
                'image' => 'root/assets/images/blog-img2.png',
                'status' => 'published',
            ],
            [
                'title' => 'CLP ONLINE ANNUAL EVENT ON OCTOBER 3, 2020',
                'slug' => 'clp-online-event',
                'summary' => 'CLP’s 2020 annual event was held online. The program began with the national anthems of the USA and Bangladesh. Important speech was given by personalities such as writer and teacher Dr. Zafar Iqbal, CLP President Dr. Mohammad Farooque, Dnet CEO Mr. ABM Sirajul Hossain.',
                'description' => 'CLP’s 2020 annual event was held online. The program began with the national anthems of the USA and Bangladesh. Important speech was given by personalities such as writer and teacher Dr. Zafar Iqbal, CLP President Dr. Mohammad Farooque, Dnet CEO Mr. ABM Sirajul Hossain.',
                'date' => 'NOV 03, 2020',
                'youtube_url' => null,
                'image' => 'root/assets/images/program.png',
                'status' => 'published',
            ],
            [
                'title' => 'CLP TEACHERS TRAINING DURING COVID 19 PANDEMIC',
                'slug' => 'clp-online-annual-event-on-october-3-2020',
                'summary' => 'CLP has provided online training to 33 teachers from five different institutions during the COVID-19 pandemic. The teachers are very optimistic about utilizing the acquired pedagogical and technical skills in the classrooms. The next on the agenda is conducting a refreshers’ training for the project teachers of CLP’s 79 supported schools.',
                'description' => 'CLP has provided online training to 33 teachers from five different institutions during the COVID-19 pandemic. The teachers are very optimistic about utilizing the acquired pedagogical and technical skills in the classrooms. The next on the agenda is conducting a refreshers’ training for the project teachers of CLP’s 79 supported schools.',
                'date' => 'NOV 03, 2020',
                'youtube_url' => null,
                'image' => 'root/assets/images/clp-training.png',
                'status' => 'published',
            ],
            [
                'title' => 'CLC & SCR ESTABLISHMENT CONTINUED DURING COVID 19 PANDEMIC',
                'slug' => 'clc-&-scr-establishment-continued-during-covid-19-pandemic',
                'summary' => 'Even during the time of the COVID 19 pandemic, Dnet (CLPs Bangladesh partner) continued its center establishment operation. Following COVID-19 safety guidelines, five CLCs and six SCRs have been established in five different institutions.',
                'description' => 'Even during the time of the COVID 19 pandemic, Dnet (CLPs Bangladesh partner) continued its center establishment operation. Following COVID-19 safety guidelines, five CLCs and six SCRs have been established in five different institutions.',
                'date' => 'NOV 03, 2020',
                'youtube_url' => null,
                'image' => 'root/assets/images/scr-photo.jpg',
                'status' => 'published',
            ],
            [
                'title' => 'MODULE DEVELOPMENT FOR TEACHERS TRAINING',
                'slug' => 'module-development',
                'summary' => 'Recently CLP has developed multiple manuals of several online applications which can be used for taking online classes. Selected teachers from all the CLP supported schools will soon be given training on how to use these applications effectively.',
                'description' => 'Recently CLP has developed multiple manuals of several online applications which can be used for taking online classes. Selected teachers from all the CLP supported schools will soon be given training on how to use these applications effectively.',
                'date' => 'DEC 21, 2020',
                'youtube_url' => null,
                'image' => 'root/assets/images/module.jpg',
                'status' => 'published',
            ],
            [
                'title' => 'RECENT CENTER ESTABLISHMENTS',
                'slug' => 'recent-center-establishments',
                'summary' => 'On November 08, 2020, 1 CLC and 2 SCRs have been set up in Krishnapur Government Primary School, Sherpur, Bogura. 1 distance classroom has been set up in Siddika Begum Girls High School, Chandpur on December 14, 2020 and another in Ghorashal Pilot High School on December 17, 2020.',
                'description' => 'On November 08, 2020, 1 CLC and 2 SCRs have been set up in Krishnapur Government Primary School, Sherpur, Bogura. 1 distance classroom has been set up in Siddika Begum Girls High School, Chandpur on December 14, 2020 and another in Ghorashal Pilot High School on December 17, 2020.',
                'date' => 'DEC 21, 2020',
                'youtube_url' => null,
                'image' => 'root/assets/images/recent.jpg',
                'status' => 'published',
            ],
            [
                'title' => 'TEACHERS TRAINING ON EFFECTIVE ONLINE CLASS CONDUCTION',
                'slug' => 'teachers-training-on-effective-online-class-conduction',
                'summary' => 'CLP has started providing training to its supported schools’ teachers on online class conduction. Teachers are participating in the training using online platforms.',
                'description' => 'CLP has started providing training to its supported schools’ teachers on online class conduction. Teachers are participating in the training using online platforms.',
                'date' => 'JAN 04, 2021',
                'youtube_url' => null,
                'image' => 'root/assets/images/day1.jpg',
                'status' => 'published',
            ],
            [
                'title' => 'CLP LAUNCHED ENGLISH LANGUAGE SKILLS DEVELOPMENT COURSE',
                'slug' => 'clp-launched-english-language-skills-development-course',
                'summary' => 'CLP has incorporated a brand-new program titled as ‘Distance Learning’ in DMNAPK, Gazipur, Bangladesh, designed following the Blended Learning Method. This method allows the students immense convenience and flexibility to learn within a joyful environment, and also increases their will for learning new things. ',
                'description' => 'CLP has incorporated a brand-new program titled as ‘Distance Learning’ in DMNAPK, Gazipur, Bangladesh, designed following the Blended Learning Method. This method allows the students immense convenience and flexibility to learn within a joyful environment, and also increases their will for learning new things. ',
                'date' => 'FEB 15, 2021',
                'youtube_url' => null,
                'image' => 'root/assets/images/DMNAPK-Distanc-class.jpg',
                'status' => 'published',
            ],
            [
                'title' => 'COMPUTER LITERACY CENTER ESTABLISHED IN KASHBAMAJAIL A.H. HIGH SCHOOL, RAJBARI',
                'slug' => 'computer-literacy-center-established-in-kashbamajail',
                'summary' => 'Covid-19 has disrupted daily operations all across the world. Regardless of Covid-19, as part of its ongoing activities, CLP opens a new Computer Literacy Center on March 2, 2021 at Kashbamajail A.H. High School. The center is in Pangsha, a rural area in Bangladesh&apos;s Rajbari district.',
                'description' => 'Covid-19 has disrupted daily operations all across the world. Regardless of Covid-19, as part of its ongoing activities, CLP opens a new Computer Literacy Center on March 2, 2021 at Kashbamajail A.H. High School. The center is in Pangsha, a rural area in Bangladesh&apos;s Rajbari district.',
                'date' => 'MARCH 03, 2021',
                'youtube_url' => null,
                'image' => 'root/assets/images/123.png',
                'status' => 'published',
            ],
            [
                'title' => 'BRIEF OVERVIEW OF CLP',
                'slug' => 'brief-overview-of-clp',
                'summary' => 'CLP recently developed a short video documentary outlining the organizations journey and all of its programs.',
                'description' => 'CLP recently developed a short video documentary outlining the organizations journey and all of its programs.',
                'date' => 'APRIL 04, 2021',
                'youtube_url' => 'https://www.youtube.com/embed/xGBxpFrQ7gM',
                'image' => null,
                'status' => 'published',
            ],
            [
                'title' => 'CLP TAUGHT ME TO DREAM',
                'slug' => 'clp-taught-me-to-dream',
                'summary' => 'At the beginning of the 21st century, computers were a supernatural thing in the remote areas of Bangladesh and Amla Sadarpur in Kushtia, Bangladesh was such region.',
                'description' => 'At the beginning of the 21st century, computers were a supernatural thing in the remote areas of Bangladesh and Amla Sadarpur in Kushtia, Bangladesh was such region.',
                'date' => 'APRIL 18, 2021',
                'youtube_url' => 'https://www.youtube.com/embed/GouSVFL8F4w',
                'image' => null,
                'status' => 'published',
            ],
            [
                'title' => 'CLP DONOR-TEACHER VIRTUAL CONFERENCE',
                'slug' => 'clp-donor-teacher-virtual-conference',
                'summary' => 'A virtual conference was held on May 29, 2021, in participation with the donors, teachers, and CLP volunteers to establish a stronger connection between the donors and their supported schools. CLP’s role in the upcoming pandemic days has also been discussed at the conference.',
                'description' => 'A virtual conference was held on May 29, 2021, in participation with the donors, teachers, and CLP volunteers to establish a stronger connection between the donors and their supported schools. CLP’s role in the upcoming pandemic days has also been discussed at the conference.',
                'date' => 'MAY 30, 2021',
                'youtube_url' => null,
                'image' => 'root/assets/images/vc.jpg',
                'status' => 'published',
            ],
            [
                'title' => 'COMPUTER LITERACY CENTER AND DISTANCE CLASSROOM FOUNDED AT G. K. ADARSHA HIGH SCHOOL, GAZIPUR',
                'slug' => 'distance-classroom-founded-adarsha-high-school',
                'summary' => 'CLPs 280th Computer Literacy Center (CLC) has been founded at G. K. Adarsha High School, Gazipur, as part of its aim to empower underprivileged youth by way of modern computer education in Bangladesh. As well, a distant classroom has been established to help out students in cultivating their English communication abilities as well as providing progressive co-operative learning.',
                'description' => 'CLPs 280th Computer Literacy Center (CLC) has been founded at G. K. Adarsha High School, Gazipur, as part of its aim to empower underprivileged youth by way of modern computer education in Bangladesh. As well, a distant classroom has been established to help out students in cultivating their English communication abilities as well as providing progressive co-operative learning. ',
                'date' => 'JUNE 15, 2021',
                'youtube_url' => null,
                'image' => 'assets/images/n1.jpg',
                'status' => 'published',
            ],
            [
                'title' => 'EXCLUSIVE INTERVIEW OF CLP USA PRESIDENT DR. MOHAMMAD FAROOQUE AT NEW YORK JOURNAL',
                'slug' => 'exclusive-interview-of-clp-usa-president-dr-mohammad-farooque',
                'summary' => 'CLP USA president Dr. Mohammad Farooque recently gave an exclusive interview to the New York Journal - a show on the prominent North American TV channel "Deshebideshe" about renowned Bangladeshi Americans. The program highlights how the renowned Bangladeshi-American Dr. Mohammad Farooque continues to play a major role in supporting our society in environmental, social, humanitarian and technological advancements.',
                'description' => 'CLP USA president Dr. Mohammad Farooque recently gave an exclusive interview to the New York Journal - a show on the prominent North American TV channel "Deshebideshe" about renowned Bangladeshi Americans. The program highlights how the renowned Bangladeshi-American Dr. Mohammad Farooque continues to play a major role in supporting our society in environmental, social, humanitarian and technological advancements.',
                'date' => 'JULY 18, 2021',
                'youtube_url' => 'https://www.youtube.com/embed/q9POfjxHkEs',
                'image' => null,
                'status' => 'published',
            ],
            [
                'title' => 'AN IMPRESSIVE LIBRARY HAS BEEN SET UP AT KRISHNAPUR GOVT. PRIMARY SCHOOL',
                'slug' => 'an-impressive-library-has-been-set-up-at-krishnapur govt-primary-school',
                'summary' => 'Computer Literacy Program (CLP) USA has set up a library in Krishnapur Govt. Primary School, Sherpur, Bogura with an aim of spreading light of knowledge among the students of remote areas. Dr. Molla Fazlul Huq, a heartfelt Bangladeshi living in the United States, is the patron of this library.',
                'description' => 'Computer Literacy Program (CLP) USA has set up a library in Krishnapur Govt. Primary School, Sherpur, Bogura with an aim of spreading light of knowledge among the students of remote areas. Dr. Molla Fazlul Huq, a heartfelt Bangladeshi living in the United States, is the patron of this library.',
                'date' => 'JUNE 23, 2021',
                'youtube_url' => null,
                'image' => 'root/assets/images/l11.jpg',
                'status' => 'published',
            ],
            [
                'title' => 'CLP ORGANIZED AN ONLINE PRIMARY SCHOOL TEACHERS TRAINING IN COLLABORATION WITH A PARTNER ORGANIZATION FERA FOUNDATION (NEW YORK), A US CHARITY ORGANIZATION',
                'slug' => 'training-collaboration-with-partner-organization-fera-foundation',
                'summary' => 'On the 25th of August 2021, CLP hosted an online primary school teachers training focusing on Student Engagement Strategies. Fera Foundation volunteer, Ms. Israt Nali, an experienced teacher trainer from the New York City Education system facilitated the training-of-teachers via Zoom.',
                'description' => 'On the 25th of August 2021, CLP hosted an online primary school teachers training focusing on Student Engagement Strategies. Fera Foundation volunteer, Ms. Israt Nali, an experienced teacher trainer from the New York City Education system facilitated the training-of-teachers via Zoom.',
                'date' => 'AUGUST 26, 2021',
                'youtube_url' => null,
                'image' => 'root/assets/images/news.jpg',
                'status' => 'published',
            ],
            [
                'title' => 'CLP HAS SET UP A SMART CLASSROOM AT BHABERCHAR WAZIR ALI HIGH SCHOOL, MUNSHIGANJ',
                'slug' => 'clp-has-set-up-a-smart-classroom-at-bhaberchar-wazir-ali-high-school',
                'summary' => 'On September 07, 2021, CLP has established its 178th Smart Classroom (SCR) across the country and the first at Bhaberchar Wazir Ali High School, located in Bhaberchar, a rural area in Munshiganj district. Mr. Shawkat Ali Imran, lives in the United States, has sponsored this initiative for CLP.',
                'description' => 'On September 07, 2021, CLP has established its 178th Smart Classroom (SCR) across the country and the first at Bhaberchar Wazir Ali High School, located in Bhaberchar, a rural area in Munshiganj district. Mr. Shawkat Ali Imran, lives in the United States, has sponsored this initiative for CLP.',
                'date' => 'SEPTEMBER 08, 2021',
                'youtube_url' => null,
                'image' => 'root/assets/images/b1.webp',
                'status' => 'published',
            ],
            [
                'title' => 'CLP HAS ESTABLISHED A REMOTE TEACHING ENABLED CLASSROOM AT KHAMARPARA HIGH SCHOOL, TANGAIL',
                'slug' => 'clp-has-established-a-remote-teaching-enabled-classroom-at-khamarpara-high-school-tangail',
                'summary' => 'CLP has established remote teaching enabled classroom at Khamarpara High School, Tangail on 13th September, 2021. CLP initiatives to deliver modern and technology-based education to underprivileged youths in rural areas of Bangladesh. In continuation of this, on September 13, 2021, CLP has established a remote teaching enabled classroom at Khamarpara High School, Tangail.',
                'description' => 'CLP has established remote teaching enabled classroom at Khamarpara High School, Tangail on 13th September, 2021. CLP initiatives to deliver modern and technology-based education to underprivileged youths in rural areas of Bangladesh. In continuation of this, on September 13, 2021, CLP has established a remote teaching enabled classroom at Khamarpara High School, Tangail.',
                'date' => 'SEPTEMBER 14, 2021',
                'youtube_url' => null,
                'image' => 'root/assets/images/k1.webp',
                'status' => 'published',
            ],
            [
                'title' => 'NASHWAAN WINS THE PVSA GOLD AWARD',
                'slug' => 'nashwaan-wins-the-pvsa-gold-award',
                'summary' => 'CLP is pleased to announce that Nashwaan Ali Khan, a high school senior from Cerritos, California, USA and a CLP Youth Volunteer is a winner of the US President’s Voluntary Service Award (Gold) for 2021.',
                'description' => 'CLP is pleased to announce that Nashwaan Ali Khan, a high school senior from Cerritos, California, USA and a CLP Youth Volunteer is a winner of the US President’s Voluntary Service Award (Gold) for 2021.',
                'date' => 'SEPTEMBER 20, 2021',
                'youtube_url' => null,
                'image' => 'root/assets/images/n1.webp',
                'status' => 'published',
            ],
            [
                'title' => 'Computer Literacy Program (CLP) Online Annual Event 2021 Program Summary',
                'slug' => 'annual_event_21',
                'summary' => 'Computer Literacy Program (CLP) Online Annual Event 2021, scheduled as: <ul><li>USA: Friday, October 15, 2021, 9:30 PM to 11:30 PM Eastern Time.</li><li>Bangladesh: Saturday, October 16, 2021, 7:30 AM to 9:30 AM</li></ul><strong>Program summary link:</strong> <a target="_blank" style="color: black; font-size: 1.2rem; text-decoration: underline;" href="' . asset("root/fileupload/CLP-Annual-Event-2021-Program-Schedule.pdf") . '">CLP Annual Event 2021 Program Schedule</a>',
                'description' => 'Computer Literacy Program (CLP) Online Annual Event 2021, scheduled as: <ul><li>USA: Friday, October 15, 2021, 9:30 PM to 11:30 PM Eastern Time.</li><li>Bangladesh: Saturday, October 16, 2021, 7:30 AM to 9:30 AM</li></ul><strong>Program summary link:</strong> <a target="_blank" style="color: black; font-size: 1.2rem; text-decoration: underline;" href="' . asset("root/fileupload/CLP-Annual-Event-2021-Program-Schedule.pdf") . '">CLP Annual Event 2021 Program Schedule</a>',
                'date' => 'OCTOBER 14, 2021',
                'youtube_url' => null,
                'image' => 'root/assets/images/fly10.JPG',
                'status' => 'published',
            ],
            [
                'title' => 'CLP ANNUAL EVENT 2021 WAS HELD ON OCTOBER 15, 2021 AT 9.30PM EST JOURNAL',
                'slug' => 'clp-annual-event-2021-was-held-on-october-15-2021-est-journal',
                'summary' => 'CLP Annual Event 2021 was held on October 15, 2021 at 9.30PM EST. The highlights of the program: CLP Progress, New Initiatives & Entertainment. Please click on the link https://www.youtube.com/embed/Q6WtmRSrZ10 to watch the CLP Annual Event 2021.',
                'description' => 'CLP Annual Event 2021 was held on October 15, 2021 at 9.30PM EST. The highlights of the program: CLP Progress, New Initiatives & Entertainment. Please click on the link https://www.youtube.com/embed/Q6WtmRSrZ10 to watch the CLP Annual Event 2021.',
                'date' => 'OCTOBER 16, 2021',
                'youtube_url' => 'https://www.youtube.com/embed/Q6WtmRSrZ10',
                'image' => null,
                'status' => 'published',
            ],
            [
                'title' => 'CLP HAS ESTABLISHED A REMOTE TEACHING ENABLED SMART CLASSROOM AT GHORASHAL PILOT HIGH SCHOOL, NARSINGDI',
                'slug' => 'clp-has-established-a-remote-teaching-enabled-smart-classroom-at-ghorashal-pilot-high-school',
                'summary' => 'CLP initiatives bring the light of modern and technology based education to underprivileged youth in remote areas. To achieve this objective, CLP has established a remote teaching enabled classroom on 21th October, 2021 at Ghorashal Pilot High School situated in Ghorashal upazila of Narsingdi district in Bangladesh. ',
                'description' => 'CLP initiatives bring the light of modern and technology based education to underprivileged youth in remote areas. To achieve this objective, CLP has established a remote teaching enabled classroom on 21th October, 2021 at Ghorashal Pilot High School situated in Ghorashal upazila of Narsingdi district in Bangladesh. ',
                'date' => 'OCTOBER 22, 2021',
                'youtube_url' => null,
                'image' => 'root/assets/images/g1.webp',
                'status' => 'published',
            ],
            [
                'title' => 'NEW CLC AND SCR ESTABLISHED AT SHERPUR, BOGURA',
                'slug' => 'new-clc-and-scr-established-at-sherpur-bogura',
                'summary' => 'For more than sixteen years, CLP has been providing modern computer literacy to disadvantaged youth in distant areas of Bangladesh. Along the way, CLP has established smart classrooms (SCRs) and computer literacy centers (CLCs) in two different schools in Sherpur upazila of Bogura district in Bangladesh.',
                'description' => 'For more than sixteen years, CLP has been providing modern computer literacy to disadvantaged youth in distant areas of Bangladesh. Along the way, CLP has established smart classrooms (SCRs) and computer literacy centers (CLCs) in two different schools in Sherpur upazila of Bogura district in Bangladesh.',
                'date' => 'DECEMBER 08, 2021',
                'youtube_url' => null,
                'image' => 'root/assets/images/news/pourosva_clc-min.jpg',
                'status' => 'published',
            ],
            [
                'title' => 'A new Computer Literacy Center (CLC) founded at Narikel Baria ZA Secondary School, Jhenaidah',
                'slug' => 'narikelbaria-clc-establishment',
                'summary' => 'Recently Computer Literacy Program (CLP) founded a new Computer Literacy Center (CLC) at Narikel Baria ZA Secondary School, Jhenaidah on January 17, 2022. CLP has achieved another step forward in spreading computer literacy among Bangladesh&apos;s disadvantaged youth by establishing this CLC, reaching total 287 centers.',
                'description' => '<p class="work_para_news">Recently Computer Literacy Program (CLP) founded a new <a href="' . route("website.clcTeaching") . '">Computer Literacy Center (CLC)</a> at Narikel Baria ZA Secondary School, Jhenaidah on January 17, 2022. CLP has achieved another step forward in spreading computer literacy among Bangladesh&apos;s disadvantaged youth by establishing this CLC, reaching total <a href="' . route("website.schoolInfo") . '">287 centers</a>. The center is situated in Narikel Baria, a rural region in Bangladesh&apos;s Jhenaidah district. Md. Abu Jafar, a kind Bangladeshi presently residing in Canada, has extended his helping hand to disadvantaged students by sponsoring this CLC in this digital era, enabling them to pursue a modern educational life. </p><div style="box-shadow: 5px 5px 20px; border: 4px solid #f8f8ff;" class="embed-responsive embed-responsive-16by9"> <iframe class="embed-responsive-item" src="https://www.youtube.com/embed/Bya_4Ss13fM?autoplay=0&mute=0" allowfullscreen></iframe> </div> <br> <p class="work_para_news">This school currently has an enrollment of 880 students, 409 of them are female. To convey modern computer educations to the students properly by CLC center’s teachers, a teacher training program was organized to train teachers. Under the guidance of trained teachers, 8 students from one batch will be able to learn fundamental computer skills with the help of “এসো কম্পিউটার শিখি (Esho Computer Sikhi)” book. </p> <p><figure><img src="' . asset('root/assets/images/news/narkel_baria-2.jpg') . '" alt="img" class="img-responsive"><figcaption class="work_para_news">Plaque of newly established CLC at Narikel Baria ZA Secondary School, Jhenaidah</figcaption> </figure></p> <p class="work_para_news">Computer education has become deeply essential for students in today&apos;s world. The headmaster of the school expressed his sincere gratitude to the sponsor for establishing and opening the door of computer literacy education for the disadvantaged students. He also praised the fact that more of his students will now be able to learn new computer lessons at the school.</p>',
                'date' => 'JANUARY 18, 2022',
                'youtube_url' => null,
                'image' => 'root/assets/images/news/narkel_baria-1.jpg',
                'status' => 'published',
            ],
            [
                'title' => 'CLP has established a remote teaching enabled Smart Classroom at Kofejan Nesa & Hazi Niamot Ullah High School, Kushtia',
                'slug' => 'kofejan',
                'summary' => 'To foster interactive real-time remote learning and ensure technology-based effective learning for underprivileged youth, CLP has established a remote teaching enabled Smart Classroom at Kofejan Nesa & Hazi Niamot Ullah High School, Kushtia on 23rd February, 2022. The school is located at Moslempur in a remote area of Bheramara upazila of Kushtia district. This school&apos;s students were behind the times when it comes to technology-based learning.',
                'description' => '<p class="work_para_news">To foster interactive real-time remote learning and ensure technology-based effective learning for underprivileged youth, CLP has established a remote teaching enabled smart classroom at Kofejan Nesa & Hazi Niamot Ullah High School, Kushtia on 23rd February, 2022. The school is located at Moslempur in a remote area of Bheramara upazila of Kushtia district. This school&apos;s students were behind the times when it comes to technology-based learning. Bringing this smart classroom would allow 371 students (153 male and 218 female) to learn in an interesting and engaging atmosphere while also receiving lessons from skilled teachers and professionals. </p> <div style="box-shadow: 5px 5px 20px; border: 4px solid #f8f8ff;" class="embed-responsive embed-responsive-16by9"> <iframe class="embed-responsive-item" src="https://www.youtube.com/embed/QFN32E-q3sw?autoplay=0&mute=0" allowfullscreen></iframe> </div> <br> <p class="work_para_news">This remote teaching enabled smart classroom is constituted of 1 laptop, 1 smart TV, 1 microphone, 1 IPS, and 1 camera, as well as other necessary components. Considering the present world, the majority of this institution&apos;s students will benefit greatly in the years ahead since they will be able to receive distance learning from skilled instructors all over the world via the internet. </p> <p><figure><img src="' . asset('root/assets/images/news/kofejan_plaque-min.jpg') . '" alt="img" class="img-responsive"/><figcaption class="work_para_news">Plaque of newly established Remote Teaching enabled Smart Classroom at Kofejan Nesa & Hazi Niamot Ullah High School, Kushtia</figcaption> </figure></p> <p class="work_para_news">In addition, CLP has also reactivated a computer literacy center where students will now learn fundamental computer skills. This generous hand has been raised by the founder of this school Engr. Mohammad Abu Taher who is kind enough to contribute to the development of the disadvantaged. To successfully convey the current and technology-based education, Dnet&apos;s (CLP&apos;s implementing partner) official conducted a hands-on teachers training session for two teachers. Further, the head teacher of this school sincerely appreciates the patronage of this smart classroom for taking education one step further in his school.</p>',
                'date' => 'FEBRUARY 23, 2022',
                'youtube_url' => null,
                'image' => 'root/assets/images/news/kofejan_2-min.jpg',
                'status' => 'published',
            ],
            [
                'title' => 'A new CLC and distance teaching enabled smart classroom launched at Taher Secondary School, Kushtia',
                'slug' => 'taherschool',
                'summary' => 'CLP has launched a Computer Literacy Center (CLC) and distance teaching enabled smart classroom at Taher Secondary School, Kushtia on 24th February, 2022 to extend modern ICT education among underprivileged youth in Bangladesh. The school is located in a remote area of Bheramara upazila in Kushtia district of Bangladesh. We cannot think in today&apos;s world without proper computer education to keep pace with the modern world.',
                'description' => '<p class="work_para_news">CLP has launched a Computer Literacy Center (CLC) and distance teaching enabled smart classroom at Taher Secondary School, Kushtia on 24th February, 2022 to extend modern ICT education among underprivileged youth in Bangladesh. The school is located in a remote area of Bheramara upazila in Kushtia district of Bangladesh. We cannot think in today&apos;s world without proper computer education to keep pace with the modern world. Currently there are 298 students (140 boys and 158 girls) are studying in this school. With the launch of this newly built CLC, 8 students every batch would have a place to study foundational computer skills with the support of “এসো কম্পিউটার শিখি (Esho Computer Sikhi)” book and trained teachers. </p> <div style="box-shadow: 5px 5px 20px; border: 4px solid #f8f8ff;" class="embed-responsive embed-responsive-16by9"> <iframe class="embed-responsive-item" src="https://www.youtube.com/embed/KrvUgkTRmrY?autoplay=0&mute=0" allowfullscreen></iframe> </div> <br> <p class="work_para_news">The CLC center is equipped with 4 computers, 2 printers, and 2 UPS. At the same time, the distance classroom consists of 1 smart TV, 1 microphone, 1 laptop, 1 webcam and 1 IPS. The distance classroom will also facilitate as a multi-media enabled classroom, making learning more interactive and joyful to students. In additional, the incorporation of internet connectivity in this distance classroom will enable students in developing their English communication skills as well as obtaining learning from experienced teachers and experts all around the world. Engr. Mohammad Abu Taher, the school&apos;s founder, has sponsored both CLC and distance teaching enabled smart classroom. </p> <p><figure><img src="' . asset("root/assets/images/news/taher_plaque-min.png") . '" alt="img" class="img-responsive"><figcaption class="work_para_news">Plaques of newly established CLC and distance teaching enabled smart classroom at Taher Secondary School, Kushtia</figcaption> </figure></p> <p class="work_para_news">The head teacher of the school expressed his acknowledgement, saying, "We genuinely thank authorities for giving computers and its accessories and teacher training to the school. Our students will go much further in ICT and become much more skilled in working with computers as a result of CLC and distance teaching enabled smart classroom activities.” He also admired the sponsor for his charity and compassion. </p>',
                'date' => 'FEBRUARY 24, 2022',
                'youtube_url' => null,
                'image' => 'root/assets/images/news/taher-min.png',
                'status' => 'published',
            ],
            [
                'title' => 'CLP has founded a new CLC and distance teaching enabled smart classroom at Sherua Adarsha High School, Sherpur, Bogura',
                'slug' => 'sherua',
                'summary' => 'On March 20, 2022, CLP established a Computer Literacy Center (CLC) and Distance Teaching Enabled Smart Classroom at Sherua Adarsha High School located in a rural part of Sherpur upazila in Bangladesh&apos;s Bogura district to facilitate modern ICT education among disadvantaged youth.',
                'description' => ' <p class="work_para_news">On March 20, 2022, CLP established a Computer Literacy Center (CLC) and distance teaching enabled smart classroom at Sherua Adarsha High School located in a rural part of Sherpur upazila in Bangladesh&apos;s Bogura district to facilitate modern ICT education among disadvantaged youth. Dr. Molla Fazlul Haque, one of the most valuable sponsors of CLP, has again reached out to disadvantaged youth by sponsoring these both CLC and distance teaching enabled smart classroom. At present 329 students (175 boys and 158 girls) are studying in this school. The CLC center is furnished with 5 laptops, 1 smart TV and other necessary equipment. In this newly constructed CLC, 10 students from each batch would have a place to master fundamental computer skills with the help of the “এসো কম্পিউটার শিখি (Esho Computer Sikhi)” book and trained teachers. </p> <div style="box-shadow: 5px 5px 20px; border: 4px solid #f8f8ff;" class="embed-responsive embed-responsive-16by9"> <iframe class="embed-responsive-item" src="https://www.youtube.com/embed/DvvaE8K-noo?autoplay=0&mute=0" allowfullscreen></iframe> </div> <br> <p class="work_para_news">One smart classroom comprises of 1 laptop, 1 smart TV, 1 microphone; this smart classroom will function as a multi-media enabled classroom, promoting education more collaborative and interesting for students. On the other hand, the distance teaching enabled smart classroom consists of 1 laptop, 1 smart TV, 1 microphone, 1 webcam and 1 IPS. Moreover, the use of internet connectivity in this distance teaching enabled smart classroom would allow students to improve their English communication skills while also learning from experienced teachers and experts from all over the world. </p> <p class="work_para_news">Dnet&apos;s official trained 2 teachers of the school about CLP program to carry out the CLP activities smoothly and effectively. Along with that another 2 teachers were provided distance classroom management training through zoom meeting over the online. Nurul Islam Tarafder, the head teacher of the school admired the sponsor for his charity and compassion.</p>',
                'date' => 'March 20, 2022',
                'youtube_url' => 'https://www.youtube.com/embed/DvvaE8K-noo',
                'image' => null,
                'status' => 'published',
            ],
            [
                'title' => 'Connect Students Around the world (CSAW) program held in collaboration with GK Adarsha High School and Great Oaks Legacy Charter School',
                'slug' => 'csaw-news-0',
                'summary' => 'Connecting Students Around the World (CSAW) was held in collaboration with GK Adarsha High School and Great Oaks Legacy Charter School on 26th June, 2022. This is one of the most fascinating CLP programs that has brought together students from these two schools to enhance their cross-cultural interactions and the development of understanding. The program was done through joint activities and live video discussions from the two different corners of the world.',
                'description' => '<p class="work_para_news">Connecting Students Around the World (CSAW) was held in collaboration with GK Adarsha High School and Great Oaks Legacy Charter School on 26th May, 2022. This is one of the most fascinating CLP programs that has brought together students from these two schools to enhance their cross-cultural interactions and the development of understanding. The program was done through joint activities and live video discussions from the two different corners of the world. </p> <div style="box-shadow: 5px 5px 20px; border: 4px solid #f8f8ff;" class="embed-responsive embed-responsive-16by9"> <iframe class="embed-responsive-item" src="https://www.youtube.com/embed/dtR8a1Lfbn4?autoplay=0&mute=0" allowfullscreen></iframe> </div> <br> <p class="work_para_news">GK Adarsha High School is located in Dhirasrom, a remote area situated in Gazipur district of Bangladesh. On the other hand, Great Oaks Legacy Charter High School is situated in Newark City of New Jersey, USA. Both schools have created and exchanged a story video to share their school life, daily activities and culture. Following that, students from both schools introduce and share their perspectives and knowledge via a live zoom meeting. Students and teachers are happy to be part of this wonderful program and to share their thoughts and culture. </p>',
                'date' => 'May 27, 2022',
                'youtube_url' => 'https://www.youtube.com/embed/dtR8a1Lfbn4',
                'image' => null,
                'status' => 'published',
            ],
            [
                'title' => 'Another Connect Students Around the world (CSAW) program held in collaboration with Uddipon Badar Shamsu Bidya Niketon (UBSBN) and William Annin Middle School (WAMS)',
                'slug' => 'csaw-news-1',
                'summary' => 'Another Connect Students Around the world (CSAW) program was held in collaboration with Uddipon Badar Shamsu Bidya Niketon (UBSBN) and William Annin Middle School (WAMS) on 30th June, 2022. CLP launched the CSAW program in 2017 to increase cultural communication and develop understanding among young people living in different parts of the world. UBSBN is placed in a distant area of Bagerhat district called Chitoli and WAMS is located in the US state of New Jersey, far away from Bangladesh.',
                'description' => '<p class="work_para_news">Another Connect Students Around the world (CSAW) program was held in collaboration with Uddipon Badar Shamsu Bidya Niketon (UBSBN) and William Annin Middle School (WAMS) on 30th May, 2022. CLP launched the CSAW program in 2017 to increase cultural communication and develop understanding among young people living in different parts of the world. UBSBN is placed in a distant area of Bagerhat district called Chitoli and WAMS is located in the US state of New Jersey, far away from Bangladesh. </p> <div style="box-shadow: 5px 5px 20px; border: 4px solid #f8f8ff;" class="embed-responsive embed-responsive-16by9"> <iframe class="embed-responsive-item" src="https://www.youtube.com/embed/6-5850eL2yE?autoplay=0&mute=0" allowfullscreen></iframe> </div> <br> <p class="work_para_news">The program was held for the second time between the two schools. Students from both schools introduced themselves sharing their hobbies, cultures, school life through Book Creator - an online platform for creating and sharing books. </p> <p><figure><img src="' . asset("root/assets/images/news/csaw-news-1-img.png") . '" alt="img" class="img-responsive"> </figure></p> <p class="work_para_news">After that, both school students participated in a live Zoom conference to get to know one another and address one other queries. Students and instructors expressed their desire for this program to continue in the future.</p>',
                'date' => 'May 31, 2022',
                'youtube_url' => 'https://www.youtube.com/embed/6-5850eL2yE',
                'image' => null,
                'status' => 'published',
            ],
            [
                'title' => 'Pubali Bank Limited has partnered with CLP to empower disadvantaged youth through technology-aided education in Bangladesh',
                'slug' => 'csaw-news-1',
                'summary' => 'Pubali Bank Limited has partnered with CLP to empower disadvantaged youth through technology-aided education in Bangladesh. Pubali bank Limited has agreed to establish two computer literacy centers (CLCs). The CLCs will be established in Gazipur A. K. High School, Chandpur and KGS High School and College, Barishal.',
                'description' => ' <p class="work_para_news">Pubali Bank Limited has partnered with CLP to empower disadvantaged youth through technology-aided education in Bangladesh. Pubali bank Limited has agreed to establish two computer literacy centers (CLCs). The CLCs will be established in Gazipur A. K. High School, Chandpur and KGS High School and College, Barishal. Mr. Safiul Alam Khan Chowdhury, Managing Director & CEO of Pubali Bank Limited hand over the grant cheque to ATM Kamrujjaman, Joint Director of Dnet on June 16, 2022. Dnet is the implementation partner of CLP in Bangladesh. </p> <p><figure><img src="' . asset("root/assets/images/news/pubali-min.png") . '" alt="img" class="img-responsive"><figcaption class="work_para_news">Mr. Safiul Alam Khan Chowdhury, Managing Director & CEO of Pubali Bank Limited hand over the grant cheque to ATM Kamrujjaman, Joint Director of Dnet</figcaption> </figure></p>',
                'date' => 'May 31, 2022',
                'youtube_url' => null,
                'image' => 'root/assets/images/news/pubali-min.png',
                'status' => 'published',
            ],
            [
                'title' => 'CLP has established Computer Literacy Centers at Krishnakathi, Goma, Sundarkathi Secondary School in Barisal and Gazipur Kadir Aziz Lotif High School in Chandpur',
                'slug' => 'pubalibank',
                'summary' => 'Computer Literacy Program (CLP) aimed to empower underprivileged youth through computer literacy education. Following that path, CLP has established a Computer Literacy Center (CLC) and Smart Classroom (SCR) established at Belgachi Asiruddin Islmia Madrasah & Atimkhana & Lillah Bording, Belgachi, Chuadanga on 1st September 2022. The madrasah is located in a rural part of Chuadanga upazila in Bangladesh&apos;s Chuadanga district.',
                'description' => '<p class="work_para_news">On 22th August 2022, CLP has founded a CLC at Krishnakathi, Goma, Sundarkathi Secondary School and College, which is situated in rural parts of Bakerganj Upazila, Barisal. Currently about 486 students are studying in this school, out of which 246 are girls. </p> <p><figure><img src="' . asset('root/assets/images/news/1.jpg') . '" alt="img" class="img-responsive"><figcaption class="work_para_news">Glimpse of CLC at Krishnakathi, Goma, Sundarkathi Secondary School in Barisal</figcaption> </figure></p> <p class="work_para_news">Consequently, another CLC has also set up at Gazipur Kadir Aziz Lotif High School on 4th August 2022 in a far-off areas of Motlab upzilla in Chandpur. This school presently has 323 students, with 160 of whom are girls.</p> <p><figure><img src="' . asset("root/assets/images/news/2.jpg") . '" alt="img" class="img-responsive"><figcaption class="work_para_news">Glimpse of CLC at Gazipur Kadir Aziz Lotif High School in Chandpur</figcaption> </figure></p> <p class="work_para_news">Pubali Bank, one of the most prestigious banks in Bangladesh, has sponsored these two CLCs with the vision of CLP to empower the underprivileged youth through computer literacy education in these distant areas. Both CLCs are equipped with 4 laptop computers, 1 printer, 1 internet modem, and other equipment. A teacher&apos;s training was organized to explain CLC activities and give both CLC teachers introductory computer training. With the help of the trained teachers and the Eso computer sikhi book, eight students from a batch will be able to learn basic computer literacy from these two newly established CLCs.</p> <p class="work_para_news">Md. X, the X postion of Pubali Bank inaugurated the CLC at Krishnakathi, Goma, Sundarkathi Secondary School and College and Md. Y, the position of Pubali Bank inaugurated the another CLC at Gazipur Kadir Aziz Lotif High School.</p> <p><figure><img src="' . asset("root/assets/images/news/3.jpg") . '" alt="img" class="img-responsive"><figcaption class="work_para_news">Glimpse of inauguration at Gazipur Kadir Aziz Lotif High School, Chandpur</figcaption> </figure></p> <p class="work_para_news">The principal of Krishnakathi, Goma, Sundarkathi Secondary School and College, as well as the head teacher of Gazipur Kadir Aziz Lotif High School, expressed their heartfelt gratitude to the sponsor for unlocking the door to computer literacy education for their students. </p> <p><figure><img src="' . asset("root/assets/images/news/4.jpg") . '" alt="img" class="img-responsive"><figcaption class="work_para_news">Glimpse of inauguration at Krishnakathi, Goma, Sundarkathi Secondary School, Barishal</figcaption> </figure></p>',
                'date' => 'February 23, 2022',
                'youtube_url' => null,
                'image' => 'root/assets/images/news/1.jpg',
                'status' => 'published',
            ],
            [
                'title' => 'A new CLC, smart classroom and remote teaching enabled smart classroom established at Sherpur Pilot Girls High School, Sherpur',
                'slug' => 'sherpur_pilot',
                'summary' => 'CLP has established a new Computer Literacy Center (CLC) at Sherpur Pilot Girls High School on 23th August, 2022. The school is located in a rural part of Sherpur upazila in Bangladesh&apos;s Bogura district. By establishing this CLC, Sherpur got another step towards expanding computer literacy among underprivileged girls. There are now 265 girls are studying in this school.',
                'description' => '<p class="work_para_news">CLP has established a new Computer Literacy Center (CLC) at Sherpur Pilot Girls High School on 24th August, 2022. The school is located in a rural part of Sherpur upazila in Bangladesh&apos;s Bogura district. By establishing this CLC, Sherpur got another step towards expanding computer literacy among underprivileged girls. There are now 265 girls are studying in this school.</p> <p><figure><img src="' . asset("root/assets/images/news/1-min.jpg") . '" alt="img" class="img-responsive"> </figure></p> <p class="work_para_news">The CLC center is equipped with 10 laptops, 1 printer and other necessary equipment. A teacher training program was organized to train the CLC teachers to impart modern computer education properly to the students. Under the guidance of trained teachers, 20 girls from one batch will be able to learn fundamental computer skills with the help of “এসো কম্পিউটার শিখি (Esho Computer Sikhi)” book. </p> <p class="work_para_news"> One smart classroom comprises of 1 laptop, 1 smart TV and 1 microphone; this smart classroom will function as a multi-media enabled classroom, promoting education more collaborative and interesting for students. On the other side, distance teaching enabled smart classroom have 1 laptop, 1 smart TV, 1 microphone, 1 webcam, and 1 IPS. Furhtermore, this distance teaching enabled smart classroom establishment and utilization of internet access will let students learn from expert instructors and professionals from around the world while also enhancing their English communication abilities.</p> <p><figure><img src="' . asset("root/assets/images/news/scr.png") . '" alt="img" class="img-responsive"> </figure></p> <p class="work_para_news">The District Magistrate Md. Ziaul Haque of Bogura District inaugurated this CLC and SCR. At that time, UNO (Upazila nirbahi) officer of Sherpur upazila and other dignitaries were present. </p> <p><figure><img src="' . asset("root/assets/images/news/2-min.jpg") . '" alt="img" class="img-responsive"> </figure></p> <p class="work_para_news">The head teacher of the school expressed his sincere appreciation to the sponsor (Dr. Molla Fazlul Haque) for opening the door of computer literacy education among the disadvantaged girls. More girls from this school will now be able to learn basic computer lessons.</p>',
                'date' => 'August 24, 2022',
                'youtube_url' => null,
                'image' => 'root/assets/images/news/1-min.jpg',
                'status' => 'published',
            ],
            [
                'title' => 'A new CLC and SCR established at Belgachi Asiruddin Islmia Madrasah & Atimkhana & Lillah Bording, Belgachi, Chuadanga',
                'slug' => 'belgachi',
                'summary' => 'CLP has established a new Computer Literacy Center (CLC) at Sherpur Pilot Girls High School on 23th August, 2022. The school is located in a rural part of Sherpur upazila in Bangladesh&apos;s Bogura district. By establishing this CLC, Sherpur got another step towards expanding computer literacy among underprivileged girls. There are now 265 girls are studying in this school.',
                'description' => '<p class="work_para_news">Computer Literacy Program (CLP) aimed to empower underprivileged youth through computer literacy education. Following that path, CLP has established a Computer Literacy Center (CLC) and Smart Classroom (SCR) established at Belgachi Asiruddin Islmia Madrasah & Atimkhana & Lillah Bording, Belgachi, Chuadanga on 1st September 2022. The madrasah is located in a rural part of Chuadanga upazila in Bangladesh&apos;s Chuadanga district. </p> <div style="box-shadow: 5px 5px 20px; border: 4px solid #f8f8ff;" class="embed-responsive embed-responsive-16by9"> <iframe class="embed-responsive-item" src="https://www.youtube.com/embed/dadXIyUXI6A?autoplay=0&mute=0" allowfullscreen></iframe> </div> <br> <p class="work_para_news">About 275 students are studying in this madrasah, out of which 72 are girls. The madrasahh also has an orphanage where around 50 students are provided with opportunities to accommodation and get proper education. Mr. Iftekhar Hossain, a Bangladeshi living in the United States extended his generous hand to change the life of the students of this madrasah.</p> <p><figure><img src="' . asset("root/assets/images/news/bel-1.png") . '" alt="img" class="img-responsive"> </figure></p> <p class="work_para_news">The CLC center is equipped with 4 laptops, 1 printer and other necessary equipment. A teacher training program is organized to train CLC teachers to impart modern computer education to students properly. 8 students in a batch can learn basic computer skills under the guidance of trained teachers. To provide interactive and multimedia based education for around 275 students, the smart classroom has 1 laptop, 1 smart TV and 1 HDMI cable and 1 IPS with other necessary equipment.</p> <p><figure><img src="' . asset("assets/images/news/bel-2.jpg") . '" alt="img" class="img-responsive"> </figure></p> <p class="work_para_news">From now on students learning will be fun and enjoyable. The Assistant Commissioner (Land) Md. Mazharul Islam of Chuadanga Upzilla inaugurated this CLC and SCR. At that time, other dignitaries were also present.</p> <p><figure><img src="' . asset("assets/images/news/bel-3.png") . '" alt="img" class="img-responsive"></p> <p class="work_para_news">The Muhtamim (Director) of the madrasah expressed his sincere appreciation to the sponsor for opening the door of computer literacy education among the students of the madrasah. He wished for blessings and long life for the sponsor.</p>',
                'date' => 'Sep 02, 2022',
                'youtube_url' => 'https://www.youtube.com/embed/dadXIyUXI6A',
                'image' => null,
                'status' => 'published',
            ],
            [
                'title' => 'CLP has established a CLC and SCR at Darul Ulum Mohius Sunnah Madrasa, Begumganj, Noakhali',
                'slug' => 'noakhali',
                'summary' => 'CLP has established a Computer Literacy Center (CLC) and Smart Classroom (SCR) at Darul Ulum Mohius Sunnah Madrasa, Begumganj, Noakhali on 12th September 2022 with the aim to empower underprivileged youth through computer literacy education. The madrasa is situated in a rural village of Begumganj Upazila in Bangladesh&apos;s Noakhali District.',
                'description' => '<p class="work_para_news">CLP has established a Computer Literacy Center (CLC) and Smart Classroom (SCR) at Darul Ulum Mohius Sunnah Madrasa, Begumganj, Noakhali on 12th September 2022 with the aim to empower underprivileged youth through computer literacy education. The madrasa is situated in a rural village of Begumganj Upazila in Bangladesh&apos;s Noakhali District. </p> <div style="box-shadow: 5px 5px 20px; border: 4px solid #f8f8ff;" class="embed-responsive embed-responsive-16by9"> <iframe class="embed-responsive-item" src="https://www.youtube.com/embed/5JdJCrkpiXk?autoplay=0&mute=0" allowfullscreen></iframe> </div> <br> <p class="work_para_news">The newly opened CLC center is fully equipped with 3 desktop computers, 1 printer, and other appropriate infrastructure. A teacher training program has been organized to instruct CLC teachers in the proper delivery of modern computer education to students. A batch of 8 students can learn basic computer skills under the supervision of trained teachers.</p> <p class="work_para_news">About 178 underprivileged students are studying in this madrasa. Apart from that the Madrasa has an orphanage where orphan students get accommodation and quality education. To provide interactive and multimedia based education to the students, the smart classroom has 1 laptop, 1 smart TV and 1 HDMI cable and 1 IPS along with other necessary equipment. From now on students&apos; learning will be more effective, fun and enjoyable.</p> <p><figure><img src="' . asset("root/assets/images/news/noakhali-plaque.png") . '" alt="img" class="img-responsive"> </figure></p> <p class="work_para_news">Md. Riazul Islam, the madrasa&apos;s Muhtamim (Director), expressed his deepest gratitude to the sponsor for providing modernized and computer literacy education opportunities to the madrasa students.</p>',
                'date' => 'Sep 13, 2022',
                'youtube_url' => 'https://www.youtube.com/embed/5JdJCrkpiXk',
                'image' => null,
                'status' => 'published',
            ],
            [
                'title' => 'A remote teaching enabled smart classroom has been established at Taiyebunnesa Sadharan Pathagar located in Monohardi, Narsingdi',
                'slug' => 'taiyebunnesa',
                'summary' => 'A remote teaching enabled smart classroom was established on October 02, 2022 at Taiyebunnesa Sadharan Pathagar located in Monohardi, Narsingdi. In this very distant location, the library stands as the center for knowledge sharing. The remote teaching enabled smart classroom consists of 1 laptop, 1 50’ smart television, 1 webcam, 1 microphone and 1 HDMI cable.',
                'description' => '<p class="work_para_news">A remote teaching enabled smart classroom was established on October 02, 2022 at Taiyebunnesa Sadharan Pathagar located in Monohardi, Narsingdi. In this very distant location, the library stands as the center for knowledge sharing. The remote teaching enabled smart classroom consists of 1 laptop, 1 50’ smart television, 1 webcam, 1 microphone and 1 HDMI cable.</p> <p><figure><img src="'.asset("root/assets/images/news/tayub.jpg").'" alt="img" class="img-responsive"> </figure></p> <p class="work_para_news">This multimedia-equipped smart classroom will facilitate more collaborative and interactive learning among the learners and local people will be able to enhance their pursuit of knowledge by watching various educational and constructive videos in this smart classroom. Again, due to having internet connectivity in this newly established remote teaching enabled smart classroom, various expert teachers from the country and abroad will now be able to teach on various subjects which will play an important role in developing the youth society of this remote area.</p> <p><figure><img src="'.asset("root/assets/images/news/tayubp.jpg").'" alt="img" class="img-responsive"> </figure></p> <p class="work_para_news"> Dnet&apos;s representative instructed a teacher about the CLP program so that the CLP activities could be effectively carried out. Dr. Habiba Khatun, a kind Bangladeshi presently residing in the USA, has extended her helping hand to uplift this community with the digital facilities.</p>',
                'date' => 'October 03, 2022',
                'youtube_url' => null,
                'image' => 'root/assets/images/news/tayub.jpg',
                'status' => 'published',
            ],
            [
                'title' => 'COMPUTER LITERACY PROGRAM (CLP) ANNUAL EVENT 2022',
                'slug' => 'annual_event_22',
                'summary' => 'Computer Literacy Program (CLP) Annual Event 2022, scheduled as: <br> <li style="color:black">USA: Saturday, October 08, 2022, 9:30 PM to 11:30 PM Eastern Time.</li> <li style="color:black">Bangladesh: Sunday, October 09, 2022, 7:30 AM to 9:30 AM</li> <br> <strong style="color:black">Program summary link:</strong> <a target="_blank" style="color: black; font-size: 1.2rem; text-decoration: underline;" href="'.asset("root/fileupload/2022-Computer-Literacy-Program-Event-Final.pdf").'">CLP Annual Event 2022 Program Schedule</a>',
                'description' => ' <p>CLP Annual Event 2022 was held on October 08, 2022 at 9.30PM EST<br> <br> <strong style="color:black">Program summary link:</strong> <a target="_blank" style="color: black; font-size: 1.2rem; text-decoration: underline;" href="'.asset("root/fileupload/2022-Computer-Literacy-Program-Event-Final.pdf").'">CLP Annual Event 2022 Program Schedule</a> </p><div style="box-shadow: 5px 5px 20px; border: 4px solid #f8f8ff;" class="embed-responsive embed-responsive-16by9"> <iframe class="embed-responsive-item" src="https://www.youtube.com/embed/nLBwOAnXxR8?autoplay=0&mute=0" allowfullscreen></iframe> </div> <br> <br>',
                'date' => 'October 07, 2022',
                'youtube_url' => null,
                'image' => 'root/assets/images/last-original-updated-flyer-min.webp',
                'status' => 'published',
            ],
            [
                'title' => 'CLP ANNUAL EVENT 2022 WAS HELD ON OCTOBER 08, 2022 AT 9.30PM EST',
                'slug' => 'clp-annual-event-2022-was-held-on-october-08-2022',
                'summary' => 'LP Annual Event 2022 was held on October 08, 2022 at 9.30PM EST. The highlights of the program: CLP Progress, New Initiatives & Entertainment. <a style="font-weight: bold; text-decoration: underline;" target="_blank" href="https://www.youtube.com/embed/nLBwOAnXxR8">Please click here</a> to watch the CLP Annual Event 2022.',
                'description' => 'LP Annual Event 2022 was held on October 08, 2022 at 9.30PM EST. The highlights of the program: CLP Progress, New Initiatives & Entertainment. <a style="font-weight: bold; text-decoration: underline;" target="_blank" href="https://www.youtube.com/embed/nLBwOAnXxR8">Please click here</a> to watch the CLP Annual Event 2022. <br/><iframe width="532" height="304" src="https://www.youtube.com/embed/nLBwOAnXxR8" title="CLP Annual Event 2022 | @tajulimam  | Jewel Aich | @dnetvideo" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>',
                'date' => 'October 09, 2022',
                'youtube_url' => 'https://www.youtube.com/embed/nLBwOAnXxR8',
                'image' => null,
                'status' => 'published',
            ],
            [
                'title' => 'CONNECT STUDENTS AROUND THE WORLD (CSAW) PROGRAM HELD IN COLLABORATION WITH SHERUA ADARSHA HIGH SCHOOL AND GREAT OAKS LEGACY CHARTER SCHOOL',
                'slug' => 'connect-students-around-the-world-program-held-in-collaboration-with-sherua-adarsha-high-school',
                'summary' => 'Connect Students Around the world (CSAW) program was held on 5 th June. A collaboration between two countries on two sides of the world. The two participating schools are Sherua Adarsha High School(SAHS) Bangladesh and Great Oaks Legacy Charter School(GOLCS) Newark. Both schools share their stories in an online book creator platform. They share about themselves, their own tradition and their interests like their school, their village/city, sports, foods, music etc. They read each other;s stories and asked some questions. Which are then answered in a Zoom video conference.They participated in the Zoom conference on June 5, 2023 at 5 pm Bangladesh local time and 7 am local American time. After the zoom conference, they take part in informal conversations. Connect Students Around The World (CSAW) program brings together students from all over the world.This project showed how to build confidence, understanding and friendship between students living in two different corners of the world. CLP plans more similar projects in the future, using the lessons learned to benefit students around the world.',
                'description' => '<iframe width="1220" height="686" src="https://www.youtube.com/embed/qf7MPhVH-es" title="CSAW | Zoom Conference| Great Oaks &amp; Sherura School" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe> <br/> Connect Students Around the world (CSAW) program was held on 5 th June. A collaboration between two countries on two sides of the world. The two participating schools are Sherua Adarsha High School(SAHS) Bangladesh and Great Oaks Legacy Charter School(GOLCS) Newark. Both schools share their stories in an online book creator platform. They share about themselves, their own tradition and their interests like their school, their village/city, sports, foods, music etc. They read each other;s stories and asked some questions. Which are then answered in a Zoom video conference.They participated in the Zoom conference on June 5, 2023 at 5 pm Bangladesh local time and 7 am local American time. After the zoom conference, they take part in informal conversations. Connect Students Around The World (CSAW) program brings together students from all over the world.This project showed how to build confidence, understanding and friendship between students living in two different corners of the world. CLP plans more similar projects in the future, using the lessons learned to benefit students around the world.',
                'date' => 'JUNE 05, 2023',
                'youtube_url' => null,
                'image' => 'root/assets/images/a.jpg',
                'status' => 'published',
            ],
            [
                'title' => 'A New Computer Literacy Center (CLC) and a Smart Class Room (SCR) has established at Nilima Jakob College Charfassion,Bhola.',
                'slug' => 'nilima-jakob',
                'summary' => 'CLP has established a new Computer Literacy Center (CLC) and a Smart Class Room (SCR) at Nilima Jakob College Charfassion, Bhola on 29th November, 2023. The College is located in a rural part of Charfassion upazila under Bhola district in Bangladesh. By establishing this CLC and SCR Nilima Jakob College got another step towards expanding computer literacy among underprivileged youth. There are now 693 students are studying in this College.',
                'description' => '<p> <figure> <img src="'.asset("root/assets/images/news/nilima-jakob.jpeg").'" alt="img" class="img-responsive"> </figure> </p> <p class="work_para_news"> CLP has established a new Computer Literacy Center (CLC) and a Smart Class Room (SCR) at Nilima Jakob College Charfassion, Bhola on 29th November, 2023. The College is located in a rural part of Charfassion upazila under Bhola district in Bangladesh. By establishing this CLC and SCR Nilima Jakob College got another step towards expanding computer literacy among underprivileged youth. There are now 693 students are studying in this College. </p> <p class="work_para_news"> The CLC center is equipped with 4 laptops and 1 printer on the other hand one smart classroom comprises of 1 laptop, 1 smart TV, 1 HDMI cable with other necessary equipment. A teacher training program was organized to train the CLC and SCR teachers to impart modern computer education properly to the students. Under the guidance of trained teachers 8 students from one batch will be able to learn computer skills with the help of Basic course of Digital Skill Development. </p> <p class="work_para_news"> The smart classroom will function as a multi-media enabled classroom, promoting education more collaborative and interesting for students. </p> <p class="work_para_news"> The CLC teacher of the college expressed his sincere appreciation and gratefulness to the sponsor and CLP for opening the door of computer literacy education among the disadvantaged youth. </p>',
                'date' => 'November 29, 2023',
                'youtube_url' => null,
                'image' => 'root/assets/images/news/nilima-jakob.jpeg',
                'status' => 'published',
            ],
        ];
        foreach ($newsList as $nw){
            News::create($nw);
        }
    }
}
